### ISSUE TITLE
Intellij does not recognize korge-dependencyMulti

### ISSUE THREAD

**Issue by Jhovanni** [korlibs/korge#321] opened 2021-01-05 05:35 UTC
I am using a recently created project via korge plugin, I tested as well using the Project Template with same results.

After creating the project, add a dependency to korge using dependencyMulti (or dependency specifying commonMainApi). Use that dependency on code, like main.kt file. When running the project via ./gradle runJvm, the project compiles without issues, however the IDE, Intellij does not recognize the dependency added to provide code completion on other useful features. Intellij show error for the dependency files.

As example I am using jackson library, but just to demonstrate the issue. I have seen the same issue with other dependencies.

build.gradle.kts
```
...
apply<KorgeGradlePlugin>()

korge {
	...
	dependencyMulti("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.0")
	dependencyMulti("com.fasterxml.jackson.core:jackson-databind:2.11.0")

// To selectively enable targets
	targetJvm()
	...
}

```

main,kt

```
...
import com.fasterxml.jackson.databind.ObjectMapper

suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors["#2b2b2b"]) {
	val mapper = ObjectMapper()
	println("Using external dependency, result=${mapper.writeValueAsString("testValue")}")

	val minDegrees = (-16).degrees
	...
```

**As reference: I was checking [korge-samples](https://github.com/korlibs/korge-samples/blob/master/sample/luak/build.gradle.kts#L7) repository. Intellij works fine for korlibs.luak dependency.**

---
<details>
  <summary>Additional note: result of conversation about this issue on Discord channel</summary>
  
I have received feedback via discord. I got a suggestion to try the following changes. However I was not able to make it work. At the same time this structure is completely different on how the project template is organized, doesn't seem a proper solution in the long run.

Suggested build.gradle.kts content via discord.
```
plugins {
    id("com.soywiz.korge")
}

korge {
    targetJvm()
    targetJs()
}

val kotestVersion: String by project
val reflectionsVersion: String by project

kotlin {
    sourceSets {
        all {
            languageSettings.useExperimentalAnnotation("kotlin.RequiresOptIn")
            languageSettings.useExperimentalAnnotation("kotlin.ExperimentalUnsignedTypes")
        }

        getByName("jvmTest") {
            dependencies {
                implementation("io.kotest:kotest-assertions-core-jvm:$kotestVersion")
                implementation("io.kotest:kotest-runner-junit5:$kotestVersion")
                implementation("org.reflections:reflections:$reflectionsVersion")
            }
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
```

And the following settings.gradle.kts:

```
pluginManagement {
    repositories {
        mavenLocal()
        maven("https://dl.bintray.com/korlibs/korlibs")
        maven("https://plugins.gradle.org/m2/")
        mavenCentral()
        google()
        maven("https://dl.bintray.com/kotlin/kotlin-dev")
        maven("https://dl.bintray.com/kotlin/kotlin-eap")
    }

    plugins {
        id("com.soywiz.korge") version "2.0.0.2"
    }
}

rootProject.name = "project"
```
</details>

**Comment by soywiz** [comment] 2021-01-09 21:18
`dependencyMulti` is only used for korlibs. As far as I'm concerned jackson is only available on the JVM.
For stuff like that on multiplatform you will have to use: https://github.com/Kotlin/kotlinx.serialization
Korio also supports JSON and YAML parsing, but they are untyped (maps, lists, strings, booleans and numeric primitives)

**Comment by Jhovanni** [comment] 2021-01-09 22:49
Hi @soywiz , thank you for the assistance.
I didn't know that `dependencyMulti` was designed to work only for korlibs.

What is the recommended approach to include a dependency into korge. I have mentioned jackson as example, but in reality I want to use a personal dependency where I have all the logic of a game already divided in modules. Usually I'll use something like 
```
dependencies{
    implementation("me.site:my-artifiact:version)
}
```
However I am not able to find how to do it via korge plugin skeleton generated.

**Comment by soywiz** [comment] 2021-01-11 14:04
Thanks for your patience. I have already check this in detail. I had similar issues related to kotlinx.coroutines or android artifacts not being recognized. Not sure what the issue was, but maybe it is a bug in IntelliJ. The Android artifacts on korge-next used to work on linux, but were not recognized via intellij on windows or mac. I reported the issue, but with the latest version of intellij I was not able to reproduce it. 
If you plan to use your own binary dependencies I'd suggest you to publish korge-next into the .m2 folder with ./gradlew publishToMavenLocal, then check what was generated and the content of the .jar files so you can compare them. There is a .module file, .pom files and some .jar including binary stuff + the -sources.jar files. Please, check that your dependency has the same structure. Also if you can publish into github a sample as simple as possible project, we can check that one and help you troubleshooting this in the case you can't find the issue. But only with the text you have provided is hard to guess what your issue is.

Are you generating your artifact correctly? 

Korge supports a `bundle` system to include source-code dependencies easily so you don't have to compile them:  
* https://github.com/korlibs/awesome.korge.org#bundle-urls

I also created a separate plugin for including source-code dependencies:
* https://github.com/korlibs/kotlin-source-dependency-gradle-plugin

**Comment by Jhovanni** [comment] 2021-01-11 20:39
This project has been created using `gradle init` command (gradle version 6.8:
https://github.com/Jhovanni/library-example

After running `gradle build` and `gradle publishToMavenLocal`, it is published properly to local .m2 folder.

Now I use this another project, created by korge intellij plugin (version 2.0.0.0)
https://github.com/Jhovanni/korge-example

library-example dependency is added here https://github.com/Jhovanni/korge-example/blob/master/build.gradle.kts#L22. The project is able to run via `runJvm` and this log line is printed https://github.com/Jhovanni/korge-example/blob/master/src/commonMain/kotlin/main.kt#L14, but IntelliJ does not recognize de imports nor the build succeeds (even if the only target is `targetJvm()`)

Intellij do recognize de import if main is a Java file.

**Comment by Jhovanni** [comment] 2021-01-11 20:48
I have created another library project, this time using multiplatform plugin.
https://github.com/Jhovanni/multiplatform-example

When I add this dependency, previously published to maven local, via `dependencyMulti` it works. Except that it does not pull js variant, I don't know why but maybe another issue.

Based on this, it seems dependencies added to korge needs to be multiplatform since there is no method or var to add one like https://github.com/Jhovanni/library-example. As mentioned before, I have a multi-module project for game logic divided by business-related-pieces, I wonder I'll require to create several multiplatform projects in order to pull them in korge.

I haven't been able to try your suggestions. I'll rather not use a direct git commit or branch to pull dependencies since I'll continue working on the game business-engine while working on the UI. Pulling from an specific location also doesn't seem to work since I deploy de code to a repository in the cloud.

Thank you for your time, it seems I will need to create multiplatform project(s) like korlibs in order for it to work, but would like your input on it.

**Comment by Jhovanni** [comment] 2021-01-12 05:57
Well, I have been reading a lot about kotlin multi-platform projects since I haven't work with them before.
Based on research, it is not possible to use the dependency I want directly in `commonMain`, I require to create a multi-platform library as well.
I was able to use it with libgdx, but libgdx projects are not kotlin multi-platform applications.
I believe this issue can be closed, but I suggest to add something in the documentation for someone else like me without experience with multi-platform projects and want to include its own dependencies (custom/open source/commercial).

**Comment by soywiz** [comment] 2021-01-12 10:07
Your lib is a JVM library. That means that you can use it only on the JVM (you only have them available on the jvmMain source set). If you want to have other targets than JVM, you need a multiplatform Kotlin project, having at least a commonMain source set. 

You can use the source dependency plugin or publish the library binaries in a maven repo for that.

Do you have any suggestion on where could I provide this info in the documentation and how to put it in a way that could have been useful and locatable to you?

**Comment by Jhovanni** [comment] 2021-01-12 13:16
I did a search of dependencies in the documentation https://korlibs.soywiz.com/korge/#dependencies
Also went to https://korlibs.soywiz.com/faq/ to see if there was a mention of how to include personal dependencies or non-korlibs dependencies.

**Comment by soywiz** [comment] 2021-01-12 14:02
Okay. Created an issue for that.
Going to close this issue

**Closed by soywiz** 2021-01-12 14:02 UTC
Labels: check
