### ISSUE TITLE
uiButton text is broken in korge screenshot test framework

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1232] opened 2023-01-28 23:53 UTC
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/215296399-cf4b5f93-7d24-4c3d-829c-1c6b8666550e.png">

To replicate:
1. New branch from head
2. Modify something in KorgeScreenshotTest::test1
3. Notice that the ui button text appears all messed up

**Comment by soywiz** [comment] 2023-01-29 08:36
Yes. LazyBitmapFont is broken and it is caused by that. It is due to bitmap slicing being broken and figured it out after I merged something into the main branch. Sorry for the inconveniences. Im currently working on that, and since we are in alphas for a major version Im taking the opportunity to simplify stuff regarding to texture rotation/flipping etc. (check my latest wip PR).

**Comment by soywiz** [comment] 2023-02-10 12:52
This was fixed already

**Closed by soywiz** 2023-02-10 12:52 UTC
