### ISSUE TITLE
SolidRect breaks sibling bitmap with alpha channel on JVM

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#843] opened 2022-07-16 02:19 UTC
Okay I've created a MRE for https://github.com/korlibs/korge/issues/827#issuecomment-1185383018.

Code:

```
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors.MAGENTA) {
    solidRect(512, 512, Colors.WHITE).xy(256, -256)
    image(resourcesVfs["ffffff7f.png"].readBitmap()).xy(256, 256)
}
```

[ffffff7f.png](https://user-images.githubusercontent.com/4469895/179334873-7576be9c-4bd6-4450-96dd-2a21848a784f.png) is just a PNG bitmap filled with `rgba(255, 255, 255, 127)`.

Result:

![image](https://user-images.githubusercontent.com/4469895/179334902-b010f6cb-9477-4aa4-a4d9-4dec8951e720.png)

The bitmap is white with 0.5 alpha, however it is rendered as grey with 0.5 alpha.

The correct result can be obtained by making the `SolidRect` invisible in debug panel:

![image](https://user-images.githubusercontent.com/4469895/179334932-3407a872-7c4f-45d9-b037-459ab972009f.png)

I was able to work around this issue by replacing `SolidRect` with an actual white bitmap.

Note: A similar effect seems to be also happening for text rendering sometimes.

**Comment by soywiz** [comment] 2022-07-16 08:32
Woops. Thanks for reporting and helping to reproduce!

I have done some variants, one of them doesn't reproduce the issue, I will investigate the details:

```kotlin
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors.MAGENTA) {
    solidRect(256, 256, Colors.WHITE).xy(256, 0)
    //image(Bitmap32(256, 256, premultiplied = true, value = Colors["#ffffff7f"])).xy(256, 256) // Not reproduces
    image(NativeImage(256, 256, premultiplied = true).context2d { fill(Colors["#ffffff7f"]) { rect(0, 0, 512, 512) } }).xy(256, 256) // Reproduces
    //image(Bitmap32(256, 256, premultiplied = true).context2d { fill(Colors["#ffffff7f"]) { rect(0, 0, 512, 512) } }).xy(256, 256) // Reproduces
    //image(resourcesVfs["ffffff7f.png"].readBitmap()).xy(256, 256) // Reproduces
}
```

**Comment by soywiz** [comment] 2022-07-30 10:21
This seems to be fixed in the main branch with all the premultiplied-alpha fixes that were applied

**Closed by soywiz** 2022-07-30 10:21 UTC
