### ISSUE TITLE
macOS 11: Unable to load library 'OpenGL'

### ISSUE THREAD

**Issue by jlandrum** [korlibs/korge#280] opened 2020-08-25 03:39 UTC
When building with `runJvm`, the application fails to run properly on macOS 11:

```Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'OpenGL':```

It appears changes in macOS 11 change where OpenGL is available to Java. Native builds work fine but debugging cannot be used.

**Comment by soywiz** [comment] 2020-08-31 09:10
Yeah, installed big sur beta the other day and I have been able to reproduced the issue. It seems that the OpenGL framework is there, but there is no dynamic library. Probably there is a static library that compiles against metal, and that's why it works on native.
We could create a dynamic library using the OpenGL static library, or start using metal already. This will require some time since we have to figure out how to get it working on AWT.

Related issue:
https://github.com/korlibs/korgw/issues/25

**Comment by soywiz** [comment] 2020-10-10 19:36
Fixed on korge-2.0.0-alpha. Was fixed by updating JNA from 5.5.0 to 5.6.0

**Closed by soywiz** 2020-10-10 19:36 UTC
Labels: bug
