### ISSUE TITLE
Collada 3D models not displayed for JavaScript platform

### ISSUE THREAD

**Issue by krzema12** [korlibs/korge#306] opened 2020-12-14 11:37 UTC
I'm running https://github.com/korlibs/korge-samples/tree/master/sample/s3d like this:

```
./gradlew :sample:s3d:runJs
```

and the texture is displayed correctly:
![Screenshot from 2020-12-14 12-32-30](https://user-images.githubusercontent.com/3110813/102076805-99725700-3e08-11eb-9489-e065dbd1261c.png)

but not the models used in "Monkey" or "Skinning":
![Screenshot from 2020-12-14 12-32-37](https://user-images.githubusercontent.com/3110813/102076835-a4c58280-3e08-11eb-93fb-36ae8b574672.png)

Nothing interesting in JS console - this stuff is displayed from the very beginning, before opening some part of the demo with 3D model:
![image](https://user-images.githubusercontent.com/3110813/102076948-d2aac700-3e08-11eb-8241-5acc7e0105dd.png)

The COLLADA file is fetched:
![image](https://user-images.githubusercontent.com/3110813/102077059-fec64800-3e08-11eb-8634-aa30b3648294.png)

but it contains Base64 content - maybe it's intended.

For JVM, this sample app works as expected.

Could you have a look please? :)

**Comment by soywiz** [comment] 2020-12-14 14:20
It seems that 3D broke on 2.0 on all the targets. I'm a bit puzzled because of the drawElementsInstanced and the UINT constants. Both look wrong to me. Since instanced drawing was not implemented, and I removed the UINT and just used USHORT because was not available on WebGL

**Comment by krzema12** [comment] 2020-12-14 17:47
Thanks for looking into this. For the record, not all platforms are affected - works on the JVM :)

**Comment by soywiz** [comment] 2020-12-14 17:49
Actually the Collada issue is fixed on korge-next already.

But on the first screen there should be some boxes and a camera moving, and that doesn't work on any of the targets, so there is a regression there.

**Comment by krzema12** [comment] 2020-12-18 11:47
Would it be possible to backport the fix for COLLADA issue into 2.0? My project is going to be used mainly through the Web.

**Comment by soywiz** [comment] 2020-12-18 13:54
Yeah, of course. 3D part is experimental, so no guarantees between minor version even if the API is changed. The idea is to have something that is not experimental and an stable API for 3.0. But experimental 3D can be worked already. Still I do not plan to work on new 3D stuff myself until 3.0 is on the horizon, except for fixing the crates sample at least.

I'm working on the `korge-next` repository since I can change anything on any of the libraries and try it right there, and that's conveniente. But I integrate from time to time the korge-next repo into/from each repository via this tasks: https://github.com/korlibs/korlibs/blob/c9360e4be376aa924cfa34e2d77f109b167df2c0/gitools/build.gradle.kts#L62-L76

So yeah, this will be available on the next release. But I want also to check why the crates sample is not working.

**Comment by krzema12** [comment] 2020-12-26 12:29
I see that the latest release should have the COLLADA issue fixed. Since I use the KorGE Gradle plugin, do I need to wait until the plugin is updated so that it refers the newest release, or can I somehow work around it?

**Comment by soywiz** [comment] 2020-12-26 12:46
There are several ways:

* change the version in `gradle.properties` file in this repo or korge-next then execute `./gradlew publishToMavenLocal` korge plugin registers mavenLocal repo first, so it will look into the `.m2` folder first and it will work
* IIRC you can specify `korgeVersion`, `korimVersio`n etc. in your `gradle.properties` file. That should override the version

I plan to release the plugin once the deploy of korge finishes, since it failed because korinject didn't finished deploying and just reran it now

**Comment by krzema12** [comment] 2020-12-26 21:49
Thanks for publishing the new release! It did fix the issue with displaying the model, but after about a minute, it crashes with the following JS console output:

```
Object { message: "index: -1, size: 0", cause: null, name: "IndexOutOfBoundsException", stack: "captureStack@webpack-internal:///./kotlin/korge-samples-s3d.js:22424:25\nIndexOutOfBoundsException_init_$Create$_0@webpack-internal:///./kotlin/korge-samples-s3d.js:24313:17\nCompanion_0.prototype.checkElementIndex@webpack-internal:///./kotlin/korge-samples-s3d.js:5623:13\nrangeCheck@webpack-internal:///./kotlin/korge-samples-s3d.js:16941:29\nArrayList.prototype.removeAt_2@webpack-internal:///./kotlin/korge-samples-s3d.js:16820:15\nalloc_0@webpack-internal:///./kotlin/korge-samples-s3d.js:152624:37\nKmlGlJsCanvas.prototype.genBuffers_1@webpack-internal:///./kotlin/korge-samples-s3d.js:152096:35\nGlBuffer.prototype.getGlId@webpack-internal:///./kotlin/korge-samples-s3d.js:138098:10\nGlBuffer.prototype.bind_1@webpack-internal:///./kotlin/korge-samples-s3d.js:138110:25\nAGOpengl.prototype.draw_27@webpack-internal:///./kotlin/korge-samples-s3d.js:137083:26\nAG.prototype.draw_28@webpack-internal:///./kotlin/korge-samples-s3d.js:133221:17\nAG.prototype.draw$default_1@webpack-internal:///./kotlin/korge-…" }
```

It reproduces both on korge-samples and my project (https://github.com/krzema12/stair-lift-simulator/commit/5d7e58cacea7fcc145c2e7cbba198e8c6267e680). Let me know if it reproduces on your side. If not, I'll do my best to attach the source maps to decipher the stack trace.

**Comment by soywiz** [comment] 2020-12-28 00:39
Reproduced. Thanks for reporting Checking already 👀

**Closed** 2020-12-28 02:19 UTC
Labels: bug, regression

**Comment by soywiz** [comment] 2020-12-28 02:22
Please, to try it:

```
git clone git@github.com:korlibs/korge-next.git
cd korge-next
./gradlew publishJsPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishJvmPublicationToMavenLocal
```

then update your project to use:

```
...
    dependencies {
        classpath("com.soywiz.korlibs.korge.plugins:korge-gradle-plugin:2.0.0.999")
    }
....
```

![2020-12-28 (1)](https://user-images.githubusercontent.com/570848/103185250-d2f09b00-48bb-11eb-80a3-2449b75c8145.png)

**Comment by soywiz** [comment] 2020-12-28 17:01
In next JVM I have also fixed strange artifacts that appeared due to precision loss and added multisampling to match the quality on the webgl target

**Comment by krzema12** [comment] 2020-12-28 20:02
Thanks, works like a charm! Waiting for the next release, and in the meantime I'll use korge-next.
