### ISSUE TITLE
ClipContainer clipping incorrectly with filter applied

### ISSUE THREAD

**Issue by sahilbajaj** [korlibs/korge#406] opened 2021-11-23 06:30 UTC
```
 override suspend fun Container.sceneMain() {

        val filterContainer = ClipContainer()

        filterContainer.setSize(400.0, 600.0)
        filterContainer.pos = Point(100.0, 100.0)

        this.addChild(filterContainer)

        val image = Image(resourcesVfs["test_image.jpg"].readBitmap().slice())
        image.setSize(400.0, 600.0)
        filterContainer.addChild(image)

        val filter = LUTFilter("underwater.png")
        filterContainer.addFilter(filter)
 }
```
Correct output, When no translation is applied.
<img width="510" alt="Screenshot 2021-11-23 at 11 36 18 AM" src="https://user-images.githubusercontent.com/4324550/142979763-a8a848bf-5fb6-43fb-b08e-2bf0efadec79.png">

Incorrect output, when a translation of 100,100 is applied
<img width="514" alt="Screenshot 2021-11-23 at 11 37 56 AM" src="https://user-images.githubusercontent.com/4324550/142979781-37210ec1-9bd5-4275-98d6-03b8bc858868.png">

**Comment by soywiz** [comment] 2022-01-31 19:35
@sahilbajaj Can't reproduce. I have tried with `ColorMatrixFilter` and `BlurFilter` since I don't have the `LUTFilter`, and it seems to work properly.

<img width="1121" alt="Screenshot 2022-01-31 at 20 34 41" src="https://user-images.githubusercontent.com/570848/151860404-0f84489d-9f1b-4b93-9744-13fdb034a3c0.png">

**Comment by sahilbajaj** [comment] 2022-01-31 19:51
I think it only happens when the virtual canvas size (aspect ratio) is different from Viewport.
I see that the default virtual canvas is same as Viewport.
Could you try that?

**Comment by sahilbajaj** [comment] 2022-01-31 19:55
basically I feel the clip computation goes haywire in that case

**Comment by soywiz** [comment] 2022-01-31 19:58
intI have tried to provide a different aspect ratio and resolution for the virtual and window dimension + additionally resizing the window. Still can't reproduce:

<img width="1196" alt="Screenshot 2022-01-31 at 20 57 15" src="https://user-images.githubusercontent.com/570848/151863599-812e51ab-3301-455b-829b-e762103f9b29.png">

**Comment by sahilbajaj** [comment] 2022-01-31 20:04
Interesting.
Let us try to figure out what went wrong on our side.

Thanks for the prompt response.
Will keep you posted.

**Comment by soywiz-invideo** [comment] 2022-02-16 11:34
From what we talked, I believe this is fixed already. Let me close this, but feel free to reopen it if it is not the case.

**Closed by soywiz-invideo** 2022-02-16 11:34 UTC
