### ISSUE TITLE
[DragonBones] _parseZOrderFrame crash in Android

### ISSUE THREAD

**Issue by yunlinos** [korlibs/korge#509] opened 2022-06-30 12:19 UTC
The crash log is as follows：

```shell
W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=45; index=-1
W/System.err:     at com.dragonbones.parser.ObjectDataParser._parseZOrderFrame(ObjectDataParser.kt:1662)
W/System.err:     at com.dragonbones.parser.ObjectDataParser$_parseAnimation$1.invoke(ObjectDataParser.kt:964)
W/System.err:     at com.dragonbones.parser.ObjectDataParser$_parseAnimation$1.invoke(ObjectDataParser.kt:964)
W/System.err:     at com.dragonbones.parser.ObjectDataParser._parseTimeline(ObjectDataParser.kt:1332)
W/System.err:     at com.dragonbones.parser.ObjectDataParser._parseTimeline$default(ObjectDataParser.kt:1238)
W/System.err:     at com.dragonbones.parser.ObjectDataParser._parseAnimation(ObjectDataParser.kt:961)
W/System.err:     at com.dragonbones.parser.ObjectDataParser._parseArmature(ObjectDataParser.kt:483)
W/System.err:     at com.dragonbones.parser.ObjectDataParser.parseDragonBonesData(ObjectDataParser.kt:2408)
W/System.err:     at com.dragonbones.factory.BaseFactory.parseDragonBonesData(factory.kt:352)
W/System.err:     at com.dragonbones.factory.BaseFactory.parseDragonBonesData$default(factory.kt:350)
```

`zOrders[index] = originalIndex++`, it will crash when index < 0.

the zOrders data is:

```json
"zOrder": {
     "frame": [
         {
             "zOrder": [],
             "duration": 35,
             "tweenEasing": null
         },
         {
             "zOrder": [
                 0,
                 2,
                 6,
                 -7,
                 8,
                 -9
             ],
             "duration": 5,
             "tweenEasing": null
         },
         {
             "zOrder": [
                 0,
                 2,
                 6,
                 -7,
                 8,
                 -9
             ],
             "duration": 5,
             "tweenEasing": null
         },
         {
             "zOrder": [
                 0,
                 2,
                 6,
                 -7,
                 8,
                 -9
             ],
             "duration": 58,
             "tweenEasing": null
         },
         {
             "zOrder": [
                 0,
                 2,
                 6,
                 -7,
                 8,
                 -9
             ],
             "duration": 5,
             "tweenEasing": null
         },
         {
             "zOrder": [
                 0,
                 2,
                 6,
                 -7,
                 8,
                 -9
             ],
             "duration": 32,
             "tweenEasing": null
         }
     ]
 },
```

The solution is：

https://forum.cocos.org/t/creator2-0-9/77284/4

https://forum.cocos.org/t/ios/75811

https://blog.csdn.net/weixin_39846664/article/details/111180190

**Comment by soywiz** [comment] 2022-06-30 18:48
So I can expect this is the place to do the fix? https://github.com/korlibs/korge/blob/ea47af1bffa826b4a4b2bed1f625213dbad03285/korge-dragonbones/src/commonMain/kotlin/com/dragonbones/parser/ObjectDataParser.kt#L1661

Is by chance a simple way of reproduce this issue via code, to add a unittest?

**Comment by yunlinos** [comment] 2022-07-01 07:42
yes, the solution in the links is ok, and you can test it with the zOrder Data above.

Another question, I used the 2.7.0 version to play DragonBones, and found that the display was very blurred, but the 3.0.0-beta5 is normal. Is there any plan to release the 3.0.0 release version?

**Comment by soywiz** [comment] 2022-07-01 10:11
@yunlinos 

Fix: nice, do you have by any chance a small reproducer of the bug? Like a small dragonbones file (even if the atlas is provided as an empty image), and a small snipet of code reproducing the issue? When fixing bugs I like to add regression tests to know for sure it is fixed, and ensure it doesn't break again in the future

Release: 3.0.0 will be released in the following weeks. I'm still releasing some betas since I'm still changing some public APIs and those will be breaking changes, and now it is the time to do so. My initial plan is to make a final release later this month, but it will depend on the stability of everything I can achieve by then.

**Comment by yunlinos** [comment] 2022-07-01 12:24
There is a dragonbones file(**testDragonBone1/assets/resources/anim/monster/503**) you can copy the crash (https://forum.cocos.org/uploads/default/original/3X/2/2/22d779a2316875326fd5e3d770dc326006022f76.rar) in links: https://forum.cocos.org/t/ios/75811 .

```kotlin
val skeDeferred = asyncImmediately { res["503/503_ske.json"].readString() }
val texDeferred = asyncImmediately { res["503/503_tex.json"].readString() }
val imgDeferred = asyncImmediately { res["503/503_tex.png"].readBitmap().mipmaps() }

val skeJsonData = skeDeferred.await()
val texJsonData = texDeferred.await()

val dragonBonesData = Json.parse(skeJsonData) ?: throw Exception("Parse ske data error!")
factory.parseDragonBonesData(dragonBonesData)

val textureAtlasData = Json.parse(texJsonData) ?: throw Exception("Parse tex data error!")
factory.parseTextureAtlasData(textureAtlasData, imgDeferred.await())
```

**Closed** 2022-07-01 17:10 UTC
