### ISSUE TITLE
Window and Graphics scaling are broken on some resolutions (maybe because of UI scaling)

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#78] opened 2020-01-28 21:46 UTC
I create a korge window in the size of `1280 x 1024` but the resulting window has only `1262` in **width**.  
There are `18px` lost somewhere in the ether.
Started with Run JVM on Windows. I double checked, that I disabled custom app scaling in Windows settings and run with 100% at 3840 x 2160.

``` kotlin
Korge(width = 1280, height = 1024) {
````

Resulting window: `1262 x 2032` (without the gray title-bar): 
![2020-01-28_22h21_56](https://user-images.githubusercontent.com/1190109/73307338-4d351d00-421e-11ea-8a3d-2396d9d04c86.png)

The image has a size of `160` and should fit in the window `(160 * 8) = 1280`.
As you can see, the window is too small. And using the game `width` to calculate positions wont't work (I tried to position images in the center of the window).
With the titlebar, also a few px at the top are cut of. (The red border has `6` instead of `8` px).

Any idea how I can get accurate sizes in my game?

**Comment by emign** [comment] 2020-01-29 08:00
I tried it myself because I vaguely remembered some similar things. My results are now different though:

Testimage: https://i.imgur.com/U21jiXQ.png with 1280x1024

Mac JVM:
<img width="1392" alt="macjvm" src="https://user-images.githubusercontent.com/5278352/73337737-3837a880-4275-11ea-9193-e2b3ae8c7025.png">

**Comment by TobseF** [comment] 2020-01-30 23:54
Good to know, that it works on other environments. But not on Win with 4K:
![2020-01-31_00h52_00](https://user-images.githubusercontent.com/1190109/73500784-f10bfd80-43c3-11ea-8f88-7032fbdae25a.png)

**Comment by TobseF** [comment] 2020-01-31 18:50
I also tested it on a Mac. First the size was correct. But after switching different scaling methods, it broke. Even after switching bag to the initial setup there were this strange behavior: The rectangles were scaled up but the KorGE Logo didn't.

![image](https://user-images.githubusercontent.com/1190109/73565539-0cc5e100-4462-11ea-9027-257889ccb513.png)

Respecting the scaling everywhere or better ignore it completely would be a good option. Without, a game can become unplayable on different resolutions and scale values. Anyway, on my machine I found no setting which worked.

**Comment by emign** [comment] 2020-02-01 09:04
I remember an autoscaling feature: You could try this (at least for the wrong logoscale):
https://github.com/korlibs/korge/commit/c285a9f4a7ce707054571627004af8cecb0e59b6
https://github.com/korlibs/korge/blob/573ef4a7f842f7114e21afb5c2916ef3ca71c4c1/korge/src/commonMain/kotlin/com/soywiz/korge/view/Graphics.kt#L12

**Comment by TobseF** [comment] 2020-02-07 09:51
Also on the JS target, the resizing has a strange characteristics on 4K Systems.  
Especially, because the mouse input coordinates doesn't match to the screen ones.

Working on **JVM**:
<img width="628" alt="2020-02-07_10h07_15" src="https://user-images.githubusercontent.com/1190109/74016174-48950500-4992-11ea-9e56-5c750030c3c7.png">

Broken on **JS**:
<img width="825" alt="2020-02-07_10h06_40" src="https://user-images.githubusercontent.com/1190109/74016209-5480c700-4992-11ea-8e23-62a0750fb775.png">

<img width="825" alt="2020-02-07_10h13_04" src="https://user-images.githubusercontent.com/1190109/74016272-71b59580-4992-11ea-870f-ddfb20bc1af9.png">
This image shows that also the input coodinates doesn't match with the screencoordinates of the graphics:

![2020-02-07_10h47_37](https://user-images.githubusercontent.com/1190109/74019280-ad069300-4997-11ea-8f8e-7d498f17cc72.gif)

**Comment by TobseF** [comment] 2020-02-07 16:48
And the last... on my mobile:
![unnamed](https://user-images.githubusercontent.com/1190109/74047670-0a6b0600-49d1-11ea-8c0f-9e289aab7f04.png)

A little bit toooo small. 

The image of the fruit tiles are set at runtime to `Korge.width / columns` so I get a tileSie of `212 px` at a Korge-width of `1280 px`.

**Comment by TobseF** [comment] 2020-02-18 21:35
Thanks for the hint and fix fix the global and local x. This pointed me to the right direction:
I have to check everywhere which coordinate system I use.  My mistakes were:
    
1. My first wrong assumption was:
    ``` kotlin
    suspend fun main() = Korge(width = 800, height = 600) {
    println(width+ " x " + height) //this is the scaled size, which is not 800 x 600!
    ```

2. Then I did the animation with the wrong _global_ variables:
    ```kotlin
    tween(this::globalX[point.x] ...
    ```
    **VS**
    ``` kotlin
    tween(this::x[point.x] ...
    ```
3. And I needed to project my input events (until we get the new vars in the next release):
    ```
    return view.globalToLocalXY(mouseEvent.x, mouseEvent)
    ```

4. Last but not least, its good to know the the debug mouse coordinates (`debug=true`) are global ones.

The big resizing problems from the screenshots _Broken on JS:_ and _on my mobile_ are gone.
Only the small window cut off is still present.

**Comment by soywiz** [comment] 2020-02-19 06:31
Glad to hear you managed to figure out. I tried to reproduce it in the samples without luck.

Inside the `Korge {}` block you have the Stage injected as this. You can use `this.views` To access the Views singleton that includes: virtualWidth, windowWidth and variants including the border region.

Regarding to the size of the window I also noticed that om windows there is a missing row or so at the top. The client size of the window or the viewport is wrong. This should be fixed at korgw level.

**Closed** 2020-02-29 10:46 UTC
Labels: bug, sponsored
